export const strokeDashArrayOptions = [
  { value: '', label: 'Solid', pattern: '──────' },
  { value: '5 5', label: 'Dotted', pattern: '• • • • •' },
  { value: '15 10', label: 'Dashed', pattern: '— — —' },
  { value: '20 10', label: 'Long Dash', pattern: '—— ——' },
  { value: '15 15', label: 'Short Dash', pattern: '– – – –' },
  { value: '5 10 5 15', label: 'Triple Dot', pattern: '• •   • •' },
  { value: '10 2 2 2 2 2 10 2', label: 'Morse Code', pattern: '— • • • — •' },
  { value: '20 10 10 10', label: 'Zebra Stripes', pattern: '— – – —' },
  { value: '12 4 4 4 4 4', label: 'Railroad Track', pattern: '— • • — • •' },
  { value: '8 2 2 8', label: 'Wavy Effect', pattern: '– • • –' },
  { value: '5 10', label: 'Spaced Dots', pattern: '•    •    •' },
  { value: '10 5 2 5', label: 'Patterned Mix', pattern: '— – • –' },
  { value: '3 7 15 5 3 7', label: 'Barcode Style', pattern: '• – — – • –' },
];
